// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwMTHJyWn6pEfdQy4h_xG2aCkK8RzrhM',
    appId: '1:1060276482755:web:2c19ba264b9df46db6e876',
    messagingSenderId: '1060276482755',
    projectId: 'joe-shop-app',
    authDomain: 'joe-shop-app.firebaseapp.com',
    storageBucket: 'joe-shop-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNL_sbXU3rH86ReBuPRfJp99632r-0sbw',
    appId: '1:1060276482755:android:1e8a64b554c6f36eb6e876',
    messagingSenderId: '1060276482755',
    projectId: 'joe-shop-app',
    storageBucket: 'joe-shop-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI0tMWk7Wsq6ATGORLP0SGOJ1J8kdMPdQ',
    appId: '1:1060276482755:ios:5ceea5356e68997cb6e876',
    messagingSenderId: '1060276482755',
    projectId: 'joe-shop-app',
    storageBucket: 'joe-shop-app.appspot.com',
    iosClientId: '1060276482755-k3hnkmi4l7fr6jed4n59eda972i88fkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.joeShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI0tMWk7Wsq6ATGORLP0SGOJ1J8kdMPdQ',
    appId: '1:1060276482755:ios:5ceea5356e68997cb6e876',
    messagingSenderId: '1060276482755',
    projectId: 'joe-shop-app',
    storageBucket: 'joe-shop-app.appspot.com',
    iosClientId: '1060276482755-k3hnkmi4l7fr6jed4n59eda972i88fkt.apps.googleusercontent.com',
    iosBundleId: 'com.example.joeShopApp',
  );
}
